Add workaround information for Chrome Manifest v3
ably/ably-js pull request #1078
Opened 2022-11-18 15:25 UTC by Peter-Maguire

Adds some workaround suggestions for keeping a service worker alive on Chrome MV3

2022-11-18 15:28 UTC, mikelee638 commented on docs/chrome-mv3.md
> +In Manifest V3, Chrome Extensions can [no longer use background pages in favour of Service Workers](https://developer.chrome.com/docs/extensions/mv3/migrating_to_service_workers/). Chrome will [mark
*receiving

2022-11-18 16:19 UTC, Peter-Maguire commented on docs/chrome-mv3.md
> +In Manifest V3, Chrome Extensions can [no longer use background pages in favour of Service Workers](https://developer.chrome.com/docs/extensions/mv3/migrating_to_service_workers/). Chrome will [mark
Thanks, fixed

2022-11-18 18:27 UTC, mikelee638 requested changes
Overall, looks good to me! Left a couple comments.

2022-11-21 17:22 UTC, owenpearson requested changes
You should link to this file from the root README

2022-11-22 11:23 UTC, Peter-Maguire commented on docs/chrome-mv3.md
> +[Enterprise extensions will continue to work on manifest v2 until January 2024](https://developer.chrome.com/docs/extensions/mv3/mv2-sunset/). If your extension is installed as part of an enterprise
Fixed https://github.com/ably/ably-js/pull/1078/commits/8c47ceb0c6ee27369eef4c6def01f960d2fd9e2b

2022-11-22 11:23 UTC, Peter-Maguire commented on docs/chrome-mv3.md
> +### Connecting to a tab
Fixed https://github.com/ably/ably-js/pull/1078/commits/8c47ceb0c6ee27369eef4c6def01f960d2fd9e2b

2022-11-22 11:23 UTC, Peter-Maguire commented on docs/chrome-mv3.md
> +### Using alarms
I've changed the wording, I'm still not sure if I got the point across succinctly enough - let me know what you think https://github.com/ably/ably-js/pull/1078/commits/8c47ceb0c6ee27369eef4c6def01f960d2fd9e2b

2022-11-22 11:23 UTC, Peter-Maguire commented on docs/chrome-mv3.md
> +In Manifest V3, Chrome Extensions can [no longer use background pages in favour of Service Workers](https://developer.chrome.com/docs/extensions/mv3/migrating_to_service_workers/).
Fixed https://github.com/ably/ably-js/pull/1078/commits/8c47ceb0c6ee27369eef4c6def01f960d2fd9e2b

2022-11-22 11:25 UTC, Peter-Maguire commented on docs/chrome-mv3.md
> +Chrome will [mark a Service Worker as inactive even if an active websocket connection is made](https://bugs.chromium.org/p/chromium/issues/detail?id=1152255).
Fixed https://github.com/ably/ably-js/pull/1078/commits/8c47ceb0c6ee27369eef4c6def01f960d2fd9e2b

2022-11-22 16:00 UTC, mikelee638 approved these changes
LGTM! I left some minute comments..

2022-11-22 16:00 UTC, mikelee638 commented on README.md
> +Chrome extensions built with manifest v3 require Service Workers instead of background pages.
*service workers

2022-11-22 16:00 UTC, mikelee638 commented on README.md
> +This is supported in Ably via the [Web Worker build](#supported-platforms), however [workarounds](docs/chrome-mv3.md) are required to ensure Chrome does not mark the Service Worker as inactive.
*service workers

2022-11-22 16:00 UTC, mikelee638 commented on README.md
> +Chrome extensions built with manifest v3 require Service Workers instead of background pages.
*Manifest V3

2022-11-23 12:46 UTC, owenpearson approved these changes
LGTM, thanks

2022-11-23 13:01 UTC, merged