Make `Utils#inspectError` use `toString` for `Error`-like values
ably/ably-js pull request #1391
Opened 2023-07-13 13:22 UTC by lawrence-forooghian

This used to be the logic but was (presumably unintentionally) swapped in 1430d68.

Resolves #1390.

2023-07-13 13:26 UTC, sacOO7 requested changes
Small request, can we add a simple test for this in `utils.test.js`, I created that test file in the last PR. Just to make sure this doesn't happen again : )

2023-07-13 13:41 UTC, SimonWoolf approved these changes
Nice, thanks

2023-07-17 11:44 UTC, owenpearson approved these changes
LGTM, thanks

2023-07-18 11:37 UTC, lawrence-forooghian commented
@sacOO7 Thank you for the suggestion! I don't really want to spend time on writing a test for this — the codebase does not in general have unit tests for utility things, and I don't think that the consequences of a regression are particularly severe nor is another regression very likely.

2023-07-18 12:16 UTC, sacOO7 commented
> @sacOO7 Thank you for the suggestion! I don't really want to spend time on writing a test for this — the codebase does not in general have unit tests for utility things, and I don't think that the consequences of a regression are particularly severe nor is another regression very likely.

Actually, we started adding tests recently -> https://github.com/ably/ably-js/blob/main/test/realtime/utils.test.js.
I think utils are also somewhat derived from the spec, so there's nothing wrong with writing tests for them, it makes sure future changes are cross-checked for expected behavior. 

In the current case, we cannot deny the chance of regression happening, since it has happened once. Because we don't know why it happened, there is still a chance it might happen again.

Also, there's not much effort in checking if the `toString` method is called.

2023-07-18 12:20 UTC, sacOO7 approved these changes

2023-07-18 12:24 UTC, lawrence-forooghian commented
> Actually, we started adding tests recently -> https://github.com/ably/ably-js/blob/main/test/realtime/utils.test.js.

I was speaking to Owen and he said that this is not something we usually do.

> I think utils are also somewhat derived from the spec

I don't think that this piece of logging logic is.

> Also, there's not much effort in checking if the `toString` method is called.

It's a non-trivial amount of effort, which is the main reason I’m resistant to do it — I'd have to find a way of exposing the `ErrorInfo` class to the tests so that I can construct one. Maybe it's easy, maybe it's not, but I don't really want to spend the time thinking about it.

2023-07-18 12:25 UTC, merged

2023-07-24 11:50 UTC, lawrence-forooghian commented
> Hey @lawrence-forooghian
> 
> can we remember to link PRs to the jira issue they are fixing please. Happy to have a discussion about why this is required if needed.
> 
> It can be done by tagging the issue key in the title. see [ably/ably-go#596](https://github.com/ably/ably-go/pull/596) Or by adding it to the PR description. see [ably/ably-java#966](https://github.com/ably/ably-java/pull/966)
> 
> This ask is now reflected in: https://github.com/ably/engineering/blob/main/best-practices/pull-requests.md

Will do 👍