1415 tree shaking attempt 2
ably/ably-js pull request #1417
Opened 2023-08-02 21:15 UTC by lawrence-forooghian

2023-08-04 16:39 UTC, owenpearson requested changes
Code changes look fine, I thought we opted not to export a rest client without rest apis though - is there any reason someone would want to use a rest client but not call any rest apis?

2023-08-14 12:21 UTC, lawrence-forooghian commented
> Code changes look fine, I thought we opted not to export a rest client without rest apis though - is there any reason someone would want to use a rest client but not call any rest apis?

Yep, you're right. I'll look into what the best way to handle this is — we want a way for `BaseRest` to include `Rest` without it being included in its subclass `BaseRealtime`.

2023-08-15 13:20 UTC, lawrence-forooghian commented
I've split the `BaseRest` class into `BaseClient` and `BaseRest` classes, the latter of which always includes the `Rest` module. See updated class structure in cd5706290269ebafc95544df9b9d6c7692d39c3f.

I also added new commit f87184e02d4221f5e9a127a23491a7171495cf4e which removes some redundant type annotations.

2023-09-05 08:35 UTC, lawrence-forooghian commented
> i'm wondering if this could be solved by (…)

@owenpearson What's the "this" that you're referring to?

2023-11-01 15:53 UTC, owenpearson approved these changes
Looks good!

And re your last comment - I can't remember what I was referring to but it sounds like i had missed your previous comments and thought that that `BaseRest` still didn't include the rest module by default?

2023-11-01 16:07 UTC, lawrence-forooghian commented
> And re your last comment - I can't remember what I was referring to but it sounds like i had missed your previous comments and thought that that `BaseRest` still didn't include the rest module by default?

That's right — we [discussed it on Slack](https://ably-real-time.slack.com/archives/D01CGFCMG68/p1693902818761259).

2023-11-06 19:47 UTC, merged