[SDK-3975] Strip logging from modular variant of the SDK
ably/ably-js pull request #1536
Opened 2023-12-06 19:32 UTC by lawrence-forooghian

In order to reduce bundle size further, we’ve decided to strip all logging from the modular variant of the SDK, except for errors and certain network events. See commit messages for more details.

I'd welcome feedback on whether the logs that I’ve chosen to preserve (i.e. the calls to `logActionNoStrip`) are the right ones.

Resolves #1526.

2023-12-08 01:53 UTC, VeskeR requested changes
I really like the solution of actually building the syntax tree using babel, and then stripping the logs based on found expression.
This is way more reliable than relying on regular expressions to parse strings to find lines of code that are related to the Logger calls - our initial idea.

Also check my code comments

2023-12-08 13:18 UTC, lawrence-forooghian commented on Gruntfile.js
> +        const filter = new RegExp(`^${__dirname}/src/.*\.[tj]s$`);
Yeah, I was a bit lazy here, thank you for pointing it out! I've changed it, see what you think.

2023-12-08 13:19 UTC, lawrence-forooghian commented on Gruntfile.js
> +    var stripLogsPlugin = {
Sure, have done.

2023-12-11 14:01 UTC, VeskeR approved these changes
LGTM!

Let's wait for @owenpearson to take a look at logs that are preserved.

2024-01-18 17:21 UTC, lawrence-forooghian commented
> I think we ought to add some logging to the platform http clients in order to properly add tracing for http requests

Sure — I've done this in #1536, on top of which the current PR is now based.

2024-01-19 07:25 UTC, lawrence-forooghian commented
@VeskeR would you mind resolving your comments please?

2024-01-19 12:08 UTC, VeskeR commented
@lawrence-forooghian Resolved

2024-01-23 17:30 UTC, owenpearson approved these changes
looks good now 👍

2024-01-24 08:49 UTC, merged